### ISSUE TITLE
AVPacket has no member named ‘lost_packet’

### ISSUE THREAD

**Issue by NoWhereMan1979** [ruiyoua/video_decode_ffmpeg#2]
I wonder in which version of ffmpeg, AVPacket had the "lost_packet" member that you used in video_decode.cpp in VideoDecode::DecodeThreadProc()

**Comment by ruiyoua** [comment]
you need to modify ffmpeg code. please refer to ffmpeg.patch

**Comment by NoWhereMan1979** [comment]
Thanks for answer. I didn't see that patch :)
